### ISSUE TITLE
Does not work in modal window in Chrome

### ISSUE THREAD

**Issue by frodopwns** [Inndy/vue-clipboard2#21]
This won't copy text to the clipboard for me in Chrome Version 63.0.3239.132 (Official Build) (64-bit)

In Safari it works fine. Is this a known issue?

Perhaps related to 
https://github.com/zenorocha/clipboard.js/issues/527
or
https://github.com/zenorocha/clipboard.js/issues/522

**Comment by Inndy** [comment]
- Did you use callback `v-clipboard:success` and/or `v-clipboard:error`? Did they give you any response?
- Please test the same code in another browser or different version of Chrome.
- Can you provide minimal code to reproduce this bug?

**Comment by frodopwns** [comment]
@Inndy I think I've found a solution. Looks like I've been hitting this issue: https://github.com/zenorocha/clipboard.js/issues/378

solved here: https://github.com/zenorocha/clipboard.js/pull/368

**Comment by Inndy** [comment]
I don't know what happened to your code exactly since you did not provide any information except Chrome version. Can't help.

So, did you fix your code anyway?

**Comment by robmazur** [comment]
Created a pull request that should fix this. #23

**Comment by Inndy** [comment]
Feature from @robmazur has been merged. @frodopwns try it! And if you solved your problem, please close the issue :)

**Comment by matthieubrau** [comment]
Hello,
It seems the issue is not solved. Always got the problem :(
Thanks

**Comment by Inndy** [comment]
@matthieubrau please fire a new issue with a minimal reproducible example, so I can understand what happened to your code.

**Comment by Inndy** [comment]
@frodopwns If you have solved your problem, please close this issue. Or give me some update.
